[[headers]]        
  for = "/*"        
    [headers.values]
      Content-Security-Policy = "default-src 'self'; connect-src 'self' http://147.45.163.173:9999/api/auth/sign-in http://147.45.163.173:9999/api/auth/sign-up http://147.45.163.173:9999/api/auth/sign-out;"      
