[[redirects]]
  from = "/api/*"
  to = "http://147.45.163.173:9999/api/:splat"
  status = 200
  force = true

[build]
  environment = {
    REACT_APP_API_URL = "https://147.45.163.173:9999/api"
  }

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; connect-src 'self' /api*; font-src 'self' /fonts/*;"